
<!-- Generated by ai2html v0.123.4 - 2026-03-03 12:51 -->
<!-- ai file: genero-edad-ocupados.ai -->
<style media="screen,print">
#g-genero-edad-ocupados-box,
#g-genero-edad-ocupados-box .g-artboard {
	margin:0 auto;
    margin-bottom: 1rem;
    margin-top: -2%;
}
#g-genero-edad-ocupados-box p {
	margin:0;
}
#g-genero-edad-ocupados-box .g-aiAbs {
	position:absolute;
}
#g-genero-edad-ocupados-box .g-aiImg {
	position:absolute;
	top:0;
	display:block;
	width:100% !important;
}
#g-genero-edad-ocupados-box .g-aiPointText p {
	white-space:nowrap;
}
#g-genero-edad-ocupados-Mesa_de_trabajo_1 {
	position:relative;
	overflow:hidden;
}
#g-genero-edad-ocupados-Mesa_de_trabajo_1 p {
	font-family:unna, serif;
	font-weight:regular;
	line-height:48px;
	height:auto;
	opacity:1;
	letter-spacing:0em;
	font-size:0.9rem;
	text-align:left;
	color:rgb(0,0,0);
	text-transform:none;
	padding-bottom:0;
	padding-top:0;
	mix-blend-mode:normal;
	font-style:normal;
	position:static;
}
#g-genero-edad-ocupados-Mesa_de_trabajo_1 .g-pstyle0 {
	font-weight:400;
	height:48px;
	text-align:center;
}
#g-genero-edad-ocupados-Mesa_de_trabajo_1 .g-pstyle1 {
	font-family:ibm-plex-sans, sans-serif;
	font-weight:500;
	line-height:36px;
	height:36px;
	font-size:.9rem;
	text-align:right;
}
#g-genero-edad-ocupados-Mesa_de_trabajo_1 .g-pstyle2 {
	font-family:ibm-plex-sans, sans-serif;
	font-weight:500;
	line-height:36px;
	height:36px;
	font-size:.9rem;
	color:rgb(237,111,42);
}
#g-genero-edad-ocupados-Mesa_de_trabajo_1 .g-pstyle3 {
	font-family:ibm-plex-sans, sans-serif;
	font-weight:400;
	line-height:36px;
	height:36px;
	font-size:.9rem;
	text-align:right;
}
#g-genero-edad-ocupados-Mesa_de_trabajo_1 .g-pstyle4 {
	font-family:ibm-plex-sans, sans-serif;
	font-weight:700;
	height:48px;
	text-align:right;
}
#g-genero-edad-ocupados-Mesa_de_trabajo_1 .g-pstyle5 {
	font-family:ibm-plex-sans, sans-serif;
	font-weight:700;
	height:48px;
	color:rgb(237,111,42);
}
#g-genero-edad-ocupados-Mesa_de_trabajo_1 .g-pstyle6 {
	font-family:ibm-plex-sans, sans-serif;
	font-weight:400;
	height:48px;
	text-align:right;
}
#g-genero-edad-ocupados-Mesa_de_trabajo_1 .g-pstyle7 {
	font-family:ibm-plex-sans, sans-serif;
	font-weight:700;
	height:48px;
	color:rgb(255,255,255);
}

</style>

<div id="g-genero-edad-ocupados-box" class="ai2html">
	<!-- Artboard: Mesa_de_trabajo_1 -->
	<div id="g-genero-edad-ocupados-Mesa_de_trabajo_1" class="g-artboard" style="" data-aspect-ratio="2" data-min-width="0">
		<div style="padding: 0 0 50% 0;"></div>
		<img id="g-genero-edad-ocupados-Mesa_de_trabajo_1-img" class="g-genero-edad-ocupados-Mesa_de_trabajo_1-img g-aiImg" alt="" loading="lazy" src="/images/genero-edad-ocupados-Mesa_de_trabajo_1.png"/>
		<div id="g-ai0-2" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:14.921%;margin-top:-19.6px;right:51.111%;width:147px;">
			<p class="g-pstyle1">Hombres</p>
		</div>
		<div id="g-ai0-3" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:14.921%;margin-top:-19.6px;left:51.4161%;width:131px;">
			<p class="g-pstyle2">Mujeres</p>
		</div>
		<div id="g-ai0-4" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:15.082%;margin-top:-19.4px;right:0.0009%;width:90px;">
			<p class="g-pstyle3">Edad</p>
		</div>
		<div id="g-ai0-5" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:30.296%;margin-top:-26.5px;right:52.6647%;width:82px;">
			<p class="g-pstyle4">7,1</p>
		</div>
		<div id="g-ai0-6" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:30.296%;margin-top:-26.5px;left:52.2364%;width:82px;">
			<p class="g-pstyle5">0,3</p>
		</div>
		<div id="g-ai0-7" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:30.176%;margin-top:-25.9px;right:-0.0042%;width:134px;">
			<p class="g-pstyle6">16-19</p>
		</div>
		<div id="g-ai0-9" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:51.296%;margin-top:-26.5px;right:54.1802%;width:106px;">
			<p class="g-pstyle4">52,1</p>
		</div>
		<div id="g-ai0-10" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:51.296%;margin-top:-26.5px;left:52.5613%;width:82px;">
			<p class="g-pstyle5">7,7</p>
		</div>
		<div id="g-ai0-11" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:51.176%;margin-top:-25.9px;right:-0.0042%;width:134px;">
			<p class="g-pstyle6">20-24</p>
		</div>
		<div id="g-ai0-12" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:72.176%;margin-top:-25.9px;right:-0.0042%;width:134px;">
			<p class="g-pstyle6">25-54</p>
		</div>
		<div id="g-ai0-13" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:72.696%;margin-top:-26.5px;left:0.7804%;width:167px;">
			<p class="g-pstyle7">1.025,4</p>
		</div>
		<div id="g-ai0-14" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:72.696%;margin-top:-26.5px;left:58.4433%;width:130px;">
			<p class="g-pstyle5">121,3</p>
		</div>
		<div id="g-ai0-15" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:93.296%;margin-top:-26.5px;right:66.5562%;width:130px;">
			<p class="g-pstyle4">313,8</p>
		</div>
		<div id="g-ai0-16" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:93.296%;margin-top:-26.5px;left:53.7043%;width:106px;">
			<p class="g-pstyle5">31,6</p>
		</div>
		<div id="g-ai0-17" class="g-Capa_1 g-aiAbs g-aiPointText" style="top:93.176%;margin-top:-25.9px;right:-0.0001%;width:94px;">
			<p class="g-pstyle6">+55</p>
		</div>
	</div>
</div>

<!-- End ai2html - 2026-03-03 12:51 -->
